package com.example.transaction.controller;

import com.example.transaction.query.AnalyticsQueryService;
import lombok.RequiredArgsConstructor;
import org.springframework.web.bind.annotation.*;

import java.util.List;

/*
 Controller exposing analytics APIs.

 This endpoint returns aggregated loan analytics generated by the repository layer using SQL queries.
*/

@RestController
@RequestMapping("/api/v1/analytics")
@RequiredArgsConstructor
public class AnalyticsController {

    private final AnalyticsQueryService analyticsService;

    /*
     Returns loan analytics summary.
    */
    @GetMapping("/loan-summary")
    public List<Object[]> loanSummary() {

        return analyticsService.loanAnalytics();
    }
}